services:
  backend:
    build: ./backend
    networks:
      - tetris-network
    expose:
      - "8080"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - tetris-network

  reverse-proxy:
    build: ./reverse-proxy
    ports:
      - "80:80"  # Only need port 80 now
    volumes:
      - ./reverse-proxy/nginx/nginx.conf:/etc/nginx/conf.d/app.conf:ro
    networks:
      - tetris-network

networks:      
  tetris-network:
    driver: bridge